# Generated by Django 4.1.1 on 2022-11-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=50, unique=True)),
                ('photo', models.URLField(blank=True, default='', max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-categories'],
            },
        ),
        migrations.CreateModel(
            name='feedBack_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='social_media_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.URLField(blank=True, max_length=1000)),
                ('telegram', models.URLField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='job_list_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('photo', models.URLField(blank=True, default='', max_length=1000)),
                ('post_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('job_type', models.CharField(max_length=100)),
                ('recruitement_type', models.CharField(max_length=100)),
                ('advt_nbr', models.CharField(max_length=100)),
                ('vaccancies', models.IntegerField(blank=True, default='')),
                ('job_location', models.CharField(max_length=100)),
                ('salary', models.TextField(blank=True, default='')),
                ('mod_of_application', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('dates_details', models.TextField(null=True)),
                ('vaccancy_details', models.TextField(blank=True, default='')),
                ('salary_details', models.TextField(blank=True, default='')),
                ('age_limit_details', models.TextField(blank=True, default='')),
                ('qualification_details', models.TextField(blank=True, default='')),
                ('application_fee_details', models.TextField(blank=True, default='')),
                ('selection_process_details', models.TextField(blank=True, default='')),
                ('how_to_apply', models.TextField(blank=True, default='')),
                ('apply_link', models.URLField(blank=True, default='', max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobHome.categories_db')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
