# Generated by Django 4.1.1 on 2022-11-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('content_brief', models.TextField(blank=True, default='')),
                ('hd1', models.CharField(max_length=200)),
                ('content1', models.TextField(blank=True, default='')),
                ('photo1', models.URLField(blank=True, default='', max_length=1000)),
                ('hd2', models.CharField(max_length=200)),
                ('content2', models.TextField(blank=True, default='')),
                ('photo2', models.URLField(blank=True, default='', max_length=1000)),
                ('hd3', models.CharField(max_length=200)),
                ('content3', models.TextField(blank=True, default='')),
                ('photo3', models.URLField(blank=True, default='', max_length=1000)),
                ('hd4', models.CharField(max_length=200)),
                ('content4', models.TextField(blank=True, default='')),
                ('photo4', models.URLField(blank=True, default='', max_length=1000)),
                ('hd5', models.CharField(max_length=200)),
                ('content5', models.TextField(blank=True, default='')),
                ('photo5', models.URLField(blank=True, default='', max_length=1000)),
                ('hd6', models.CharField(max_length=200)),
                ('content6', models.TextField(blank=True, default='')),
                ('photo6', models.URLField(blank=True, default='', max_length=1000)),
                ('hd7', models.CharField(max_length=200)),
                ('content7', models.TextField(blank=True, default='')),
                ('photo7', models.URLField(blank=True, default='', max_length=1000)),
                ('hd8', models.CharField(max_length=200)),
                ('content8', models.TextField(blank=True, default='')),
                ('photo8', models.URLField(blank=True, default='', max_length=1000)),
                ('hd9', models.CharField(max_length=200)),
                ('content9', models.TextField(blank=True, default='')),
                ('photo9', models.URLField(blank=True, default='', max_length=1000)),
                ('hd10', models.CharField(max_length=200)),
                ('content10', models.TextField(blank=True, default='')),
                ('photo10', models.URLField(blank=True, default='', max_length=1000)),
                ('hd11', models.CharField(max_length=200)),
                ('content11', models.TextField(blank=True, default='')),
                ('photo11', models.URLField(blank=True, default='', max_length=1000)),
                ('hd12', models.CharField(max_length=200)),
                ('content12', models.TextField(blank=True, default='')),
                ('photo12', models.URLField(blank=True, default='', max_length=1000)),
                ('hd13', models.CharField(max_length=200)),
                ('content13', models.TextField(blank=True, default='')),
                ('photo13', models.URLField(blank=True, default='', max_length=1000)),
                ('hd14', models.CharField(max_length=200)),
                ('content14', models.TextField(blank=True, default='')),
                ('photo14', models.URLField(blank=True, default='', max_length=1000)),
                ('hd15', models.CharField(max_length=200)),
                ('content15', models.TextField(blank=True, default='')),
                ('photo15', models.URLField(blank=True, default='', max_length=1000)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
